#!/usr/bin/env zsh


# SEXY
GEOMETRY_COLOR_EXIT_VALUE="magenta"         # prompt symbol color when exit value is != 0
GEOMETRY_COLOR_PROMPT="yellow"              # prompt symbol color
GEOMETRY_COLOR_ROOT="red"                   # root prompt symbol color
GEOMETRY_COLOR_DIR="blue"                   # current directory color
GEOMETRY_PROMPT_PREFIX=$'\n'                # prefix prompt with a new line
GEOMETRY_PROMPT_SUFFIX=$'\n  >'             # suffix prompt
GEOMETRY_PROMPT_PREFIX_SPACER=" "           # string to place between prefix and symbol
GEOMETRY_SYMBOL_SPACER=" "                  # string to place between symbol and directory
GEOMETRY_DIR_SPACER=" "                     # string to place between directory and suffix
GEOMETRY_PLUGIN_SEPARATOR=" "               # use ' ' to separate right prompt parts
GEOMETRY_SYMBOL_PROMPT="💀"
GEOMETRY_SYMBOL_RPROMPT="◇"                 # multiline prompts
GEOMETRY_SYMBOL_EXIT_VALUE="🔥"             # displayed when exit value is != 0
GEOMETRY_SYMBOL_ROOT="👹"                   # when logged in user is root


GEOMETRY_SYMBOL_GIT_UNPULLED="⇣"              # when there are unpulled changes
GEOMETRY_SYMBOL_GIT_UNPUSHED="⇡"              # when there are unpushed changes
PROMPT_GEOMETRY_GIT_TIME=false
GEOMETRY_GIT_SEPARATOR=":"

GEOMETRY_PLUGIN_HYDRATE_COLOR=blue
GEOMETRY_PLUGIN_HYDRATE_SYMBOL=💧
GEOMETRY_PLUGIN_HYDRATE_INTERVAL=20  # interval in minutes
GEOMETRY_PLUGIN_HYDRATE_BINDKEY='^L' # wrap ^L bind to also hydrate

GEOMETRY_SYMBOL_KUBE="⎈"

GEOMETRY_PROMPT_PLUGINS=(+hydrate git)
GEOMETRY_PROMPT_PLUGINS_SECONDARY=(git)

# tell omz where it lives
export ZSH="$ANTIBODY_HOME"/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh

# quit bugging me!
DISABLE_AUTO_UPDATE="true"

# DISABLE_AUTO_UPDATE=true
# ZSH="${HOME}/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"

# === Plugins ===
antibody bundle < "$HOME/.antibody" > "$HOME/.zsh-plugins"
source "$HOME/.zsh-plugins"


# === Shell parts ===

source "$HOME/.shell/.exports"
source "$HOME/.shell/.aliases"
source "$HOME/.shell/.functions"
source "$HOME/.shell/.k8rc"

# === Secrets ===

source "$HOME/.shell/.work_secrets"
source "$HOME/.shell/.personal_secrets"
