# Histroy functions
source ~/.history.zsh

bindkey    "^[[3~"          delete-char
bindkey    "^[3;5~"         delete-char

# SETUP PATHS
declare -a dirs_to_prepend
dirs_to_prepend=(
  "/usr/bin"
  "/usr/local/sbin"
  "/usr/local/git/bin"
  "/usr/local/"
  "/usr/local/mysql/bin"
  "/sw/bin/"
  "$HOME/anaconda3/bin"
  "/Library/TeX/texbin"
  "/Applications/Postgres.app/Contents/Versions/latest/bin"
  "/usr/local/Cellar/fontforge/20170731_3/bin"
  "usr/local/opt/imagemagick@6/bin"
)


# Explicitly configured $PATH
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

for dir in ${(k)dirs_to_prepend[@]}
do
  if [ -d ${dir} ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="${dir}:$PATH"
  fi
done

unset dirs_to_prepend

export PATH


# Path to your oh-my-zsh installation.
# export ZSH="$HOME/.oh-my-zsh"

# CASE_SENSITIVE="false"
# HYPHEN_INSENSITIVE="false"



# Oh My ZSH plugins
# plugins=(
# 	gitfast
# 	git-extras
# 	django
# 	osx
# 	python
# 	brew
# 	extract
# 	rake
# 	rvm
# 	ruby
# 	rails
# 	postgres
# 	thefuck)


# Source me up
# source $ZSH/oh-my-zsh.sh
source $HOME/.shell_env
# source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"


# Make less the default pager, add some options and enable syntax highlight using source-highlight
LESSPIPE=`which src-hilite-lesspipe.sh`
[ -n "$LESSPIPE" ] && export LESSOPEN="| ${LESSPIPE} %s"
less_options=(
  # If the entire text fits on one screen, just show it and quit. (Be more
  # like "cat" and less like "more".)
  --quit-if-one-screen

  # Do not clear the screen first.
  --no-init

  # Like "smartcase" in Vim: ignore case unless the search pattern is mixed.
  --ignore-case

  # Do not automatically wrap long lines.
  --chop-long-lines

  # Allow ANSI colour escapes, but no other escapes.
  --RAW-CONTROL-CHARS

  # Do not ring the bell when trying to scroll past the end of the buffer.
  --quiet

  # Do not complain when we are on a dumb terminal.
  --dumb
);
export LESS="${less_options[*]}"
export PAGER='less'

autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
  compinit -i
else
  compinit -C -i
fi
zmodload -i zsh/complist
zstyle ':completion:*' menu select # select completions with arrow keys
zstyle ':completion:*' group-name '' # group results by category
zstyle ':completion:::::' completer _expand _complete _ignored _approximate # enable approximate matches for completion
# fortune | ponysay

# export NVM_DIR="$HOME/.nvm"
# . "/usr/local/opt/nvm/nvm.sh"
